# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': 'Rome: The Eternal City',
    'game_status': 'pre-alpha',
    'game_website': 'https://rome.vineyard.haus/',
    'listing_contact': 'zeus@rome.vineyard.haus',
    'long_description': 'Rome is a roleplay-intensive MUD set during the peak '
                        'of the Roman Empire, where power, ambition, and '
                        'intrigue shape the world around you. Step into a '
                        'living, breathing recreation of ancient Rome—where '
                        'every citizen, from senator to slave, has a role to '
                        'play in the grand theater of empire. Whether you seek '
                        'glory on the battlefield as a hardened legionary, '
                        'wield influence in the Senate through cunning '
                        'diplomacy, or navigate the brutal realities of '
                        'servitude and survival, Rome offers a richly '
                        'immersive experience steeped in historical '
                        'authenticity and dramatic storytelling. With a focus '
                        'on character-driven roleplay, dynamic politics, and '
                        'player agency, this game invites you to forge your '
                        'own legacy in a world where every decision can shift '
                        'the balance of power. Will you rise, fall, or be '
                        'forgotten by history? The Eternal City awaits your '
                        'story.',
    'short_description': 'Rome is a roleplay-heavy MUD set at the height of '
                         'the Roman Empire—where politics, power, and passion '
                         'collide. Forge your destiny as a senator, soldier, '
                         'or slave in a world of intrigue, glory, and '
                         'betrayal. Your adventure awaits!',
    'telnet_hostname': 'rome.vineyard.haus',
    'telnet_port': '7530',
    'web_client_url': 'http://rome.vineyard.haus:4011/webclient/'}