# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': 'Rome: The Eternal City',
    'game_status': 'pre-alpha',
    'game_website': 'https://rome.vineyard.haus/',
    'listing_contact': 'zeus@rome.vineyard.haus',
    'long_description': 'Rome: The Eternal City is a roleplay-enforced MUD '
                        'set at the height of the Roman Empire, an age when '
                        'the gods still walk among mortals and every '
                        'citizen, from senator to slave, has a role to play '
                        'in the grand theater of empire. Staying in '
                        'character is not just encouraged here, it is '
                        'expected. Every character begins with nothing but '
                        'wits and will, and who they become from there is '
                        'entirely their own choice - the disciplined '
                        'shield-wall of a Legionary, the curse-laced rituals '
                        'of a Haruspex, the battlefield healing of a '
                        'Medicus, or several other classes besides, each '
                        'with a genuinely distinct playstyle. Choose from '
                        'six playable races, from ordinary Roman citizens to '
                        'Minotaurs, Harpies, and Cyclopes, each shaping your '
                        'character in real, mechanical ways. Combat runs on '
                        'a full turn-based system with initiative order, '
                        'wielded weapons, worn armor, status conditions, and '
                        'a real spellbook, while a genuine leveling system '
                        'rewards growth without turning the game into an '
                        'endless grind. Beyond the fighting, Rome is built '
                        'around deep, player-driven roleplay: secret cults, '
                        'public political Orders, and an active pantheon of '
                        'Twelve Olympians, plus a few older and stranger '
                        'powers, who bless, curse, and interfere directly in '
                        'mortal affairs. Rome is in active early '
                        'development, with new content, systems, and '
                        'districts added through frequent playtests and '
                        'direct community feedback. Will you rise, fall, or '
                        'be forgotten by history? The Eternal City awaits '
                        'your story.',
    'short_description': 'A roleplay-enforced Greco-Roman MUD where the '
                         'gods still walk among mortals. Rise as senator, '
                         'soldier, or sovereign in an empire built on '
                         'politics, glory, and betrayal.',
    'telnet_hostname': 'rome.vineyard.haus',
    'telnet_port': '7530',
    'web_client_url': 'http://rome.vineyard.haus:4011/webclient/'}